# Generated by Django 6.0.1 on 2026-01-21 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('university_type', models.CharField(max_length=50)),
                ('accreditation', models.CharField(max_length=20)),
                ('ranking_score', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('annual_fees', models.IntegerField()),
                ('admission_mode', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=20)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.university')),
            ],
        ),
        migrations.CreateModel(
            name='UniversityPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_type', models.CharField(max_length=100)),
                ('policy_title', models.CharField(max_length=200)),
                ('policy_description', models.TextField()),
                ('effective_year', models.IntegerField()),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.university')),
            ],
        ),
    ]
