# Generated by Django 5.1.3 on 2026-01-28 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='annual_fees',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='university',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='university',
            name='location',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='ranking_score',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='universitypolicy',
            name='effective_year',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='universitypolicy',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='universitypolicy',
            name='policy_type',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
