# Generated by Django 5.1.3 on 2026-03-05 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_accreditation_maxlength'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='actual_location',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
